name: Release

permissions:
  contents: write

on:
  push:
    branches: [master, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install

      - name: Build
        run: bun run build

      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist

      - name: Install
        run: npm i @semantic-release/git --no-save

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
